nodeLinker: node-modules
enableStrictSsl: true
enableImmutableInstalls: false

packageExtensions:
  "@rainbow-me/rainbowkit@*":
    peerDependencies:
      "@tanstack/react-query": "*"
      "react": "*"
      "react-dom": "*"
  "wagmi@*":
    peerDependencies:
      "@tanstack/react-query": "*"
      "react": "*"
      "react-dom": "*"
  "daisyui@*":
    peerDependencies:
      "postcss": "*" 